# Generated by Django 5.2.16 on 2026-07-14 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='institutions.institution')),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['institution', 'full_name'], name='students_st_institu_704b9c_idx')],
            },
        ),
    ]
