# Generated by Django 5.2.16 on 2026-07-14 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('valid', 'Valid'), ('disabled', 'Disabled'), ('not_found', 'Not Found')], max_length=16)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_attempts', to='certificates.certificate')),
            ],
            options={
                'ordering': ['-verified_at'],
                'indexes': [models.Index(fields=['certificate', 'result'], name='verificatio_certifi_63adcc_idx')],
            },
        ),
    ]
