# Generated by Django 5.2.16 on 2026-07-14 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(db_index=True, max_length=18, unique=True)),
                ('cohort_number', models.PositiveIntegerField()),
                ('degree', models.CharField(max_length=128)),
                ('program', models.CharField(max_length=128)),
                ('issued_date', models.DateField()),
                ('status', models.CharField(choices=[('grace_period', 'Grace Period'), ('anchored', 'Anchored'), ('disabled', 'Disabled')], default='grace_period', max_length=16)),
                ('chain_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='institutions.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='students.student')),
            ],
            options={
                'ordering': ['-issued_date', 'certificate_id'],
                'indexes': [models.Index(fields=['institution', 'status'], name='certificate_institu_b0d858_idx'), models.Index(fields=['institution', 'cohort_number'], name='certificate_institu_f6ec4e_idx')],
            },
        ),
    ]
