# Generated by Django 5.2.17 on 2026-08-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_disabled_at_certificate_disabled_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(db_index=True, help_text='Official certificate serial number entered by the institution', max_length=100, unique=True),
        ),
    ]
