# Generated by Django 5.2.17 on 2026-08-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='audit_activ_institu_46e9e8_idx',
            old_name='audit_activ_institu_a3f9c2_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='audit_activ_actor_i_1f8acb_idx',
            old_name='audit_activ_actor_i_e0b8d1_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='audit_activ_action_f38451_idx',
            old_name='audit_activ_action_4c7a6e_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='audit_activ_created_b8d8e7_idx',
            old_name='audit_activ_created_d2b5f8_idx',
        ),
    ]
