# Generated by Django 5.2.16 on 2026-08-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='disabled_reason',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
